### ISSUE TITLE
Service Account authentication fails on Linux, works on Mac OS X

### ISSUE THREAD

**Issue by migurski** [google/oauth2client#193] opened 2015-06-01 17:46 UTC
I am using gspread 0.2.5 and oauth2client 1.4.11. On a Mac with Python 2.7.5 I can authenticate to Google and retrieve data using this code:

```python
from oauth2client.client import SignedJwtAssertionCredentials
scopes = ['https://spreadsheets.google.com/feeds/', 'https://docs.google.com/feeds']
credentials = SignedJwtAssertionCredentials(client_email, private_key, scopes)
gc = gspread.authorize(credentials)
```

On Ubuntu 14.04 Linux with Python 2.7.6 and identical credentials, I see this error:

```python
Traceback (most recent call last):
  File "scripts/website-people-update.py", line 76, in <module>
    sheets = load_sheets(gdocs_client_email, gdocs_private_key)
  File "scripts/website-people-update.py", line 25, in load_sheets
    gc = gspread.authorize(credentials)
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 335, in authorize
    client.login()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 98, in login
    self.auth.refresh(http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 598, in refresh
    self._refresh(http.request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 769, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 834, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
AccessTokenRefreshError: invalid_grant
```

I’m at a bit of a loss. Searches for `invalid_grant` come up with solutions that address incorrect configuration, rather than platform-specific failure.

**Comment by dhermes** [comment] 2015-06-01 22:28
Yeah an invalid grant means that your refresh token is either

- no longer valid (user retracted permission)
- not associated with the client ID and secret you're using

I'm not sure what to say here. It's possible that some encoding issue has caused incorrect data to be sent.

**Comment by migurski** [comment] 2015-06-01 22:32
I don’t have a refresh token; this is a service account. The credentials I’m using are 100% for-sure correct, because they work on a Mac. What kinds of encoding issues should I be looking for?

**Comment by dhermes** [comment] 2015-06-01 22:38
Yeah I realized that after writing. I don't know what causes an invalid grant for a service account.

Is the 4-line snippet above sufficient to force the failure? How are you loading the `private_key` variable? How did you copy the file / private key value from one system to the other?

Also, can you verify the versions via:

```
$ python -c 'import oauth2client; print oauth2client.__version__'
```

**Comment by migurski** [comment] 2015-06-02 01:21
Version checks out as 1.4.11.

I’m importing the private key from a file of environment variables, using [honcho 0.6.6](https://github.com/nickstenning/honcho). The top of my file looks like this:

    gdocs_client_email = environ['GDOCS_CLIENT_EMAIL']
    gdocs_private_key = environ['GDOCS_PRIVATE_KEY'].encode('utf8')

The content of my environment file contains entries like these:

    GDOCS_CLIENT_EMAIL="nnnnnn-nnnnnn@developer.gserviceaccount.com"
    GDOCS_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nNNNNNN\nNNNNNN\nNNNNNN\n-----END PRIVATE KEY-----\n"

Honcho converts the `\n` literals into newlines, which I’ve verified by printing this.

**Comment by dhermes** [comment] 2015-06-06 17:03
I'm also at a loss. 

1. Can you give a full code snippet, including the loading of the `client_email` and `private_key` variables? I will then try to run with my own on both Ubuntu and OS X and try to reproduce.
1. Is there a reason you're using a PKCS12 key instead of a JSON service account key?

**Comment by migurski** [comment] 2015-06-07 13:59
I’m new to service accounts, so I’m pretty dim on the differences between the different kinds of keys. I don’t know why I’d use one over another, and PKCS12 was the first variant I saw an example of and got to work. I’m getting my key out of a downloaded JSON file, so I guess I’m unclear on the difference.

I am loading the two variables from the environment using [honcho](https://github.com/nickstenning/honcho), the environment file looks [as it does above](https://github.com/google/oauth2client/issues/193#issuecomment-107765444).

Here’s a complete code snippet:

```python
import os, sys, gspread, oauth2client, Crypto, honcho
from oauth2client.client import SignedJwtAssertionCredentials

assert sys.version[:5] in ('2.7.5', '2.7.6')
assert honcho.__version__ == '0.6.6'
assert oauth2client.__version__ == '1.4.11'
assert gspread.__version__ == '0.2.5'
assert Crypto.__version__ == '2.6.1'

client_email = os.environ['GDOCS_CLIENT_EMAIL']
private_key = os.environ['GDOCS_PRIVATE_KEY'].encode('utf8')

scopes = ['https://spreadsheets.google.com/feeds/', 'https://docs.google.com/feeds']
credentials = SignedJwtAssertionCredentials(client_email, private_key, scopes)
gc = gspread.authorize(credentials)
```

Works on Mac OS X 10.9.5, but fails on Ubuntu 14.04 with this error:

```
Traceback (most recent call last):
  File "google-failure.py", line 15, in <module>
    gc = gspread.authorize(credentials)
  File "/tmp/.venv/local/lib/python2.7/site-packages/gspread/client.py", line 335, in authorize
    client.login()
  File "/tmp/.venv/local/lib/python2.7/site-packages/gspread/client.py", line 98, in login
    self.auth.refresh(http)
  File "/tmp/.venv/local/lib/python2.7/site-packages/oauth2client/client.py", line 598, in refresh
    self._refresh(http.request)
  File "/tmp/.venv/local/lib/python2.7/site-packages/oauth2client/client.py", line 769, in _refresh
    self._do_refresh_request(http_request)
  File "/tmp/.venv/local/lib/python2.7/site-packages/oauth2client/client.py", line 834, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
oauth2client.client.AccessTokenRefreshError: invalid_grant
```

**Comment by dhermes** [comment] 2015-06-07 17:36
It could be a `bash` issue / encoding issue in setting the environment variable. I would strongly recommend against getting the key via `os.environ['GDOCS_PRIVATE_KEY']`. Why not just read from a file?

**Comment by migurski** [comment] 2015-06-07 18:32
Thanks! It’s definitely not an encoding error; I have added this line and the failure still happens:

    assert hashlib.md5(private_key).hexdigest() == 'ab6abff39a189497370f0362cd6abca1'

My code is being configured via environment variables, so I’d prefer to keep things out of files. I can generate them if needed, but it’s very un-preferred.

**Comment by dhermes** [comment] 2015-06-07 19:38
RE: Assertion; That's good to know / doesn't help us pinpoint the bug.
RE: Your preferences; Feel free to keep things out of files, I was just trying to pinpoint an issue.

**Comment by migurski** [comment] 2015-06-07 20:39
At least we know it’s not a bash or encoding issue with the environment!

**Comment by migurski** [comment] 2015-06-07 20:40
I’ll do some research on the JSON files, maybe there’s something there I’m missing that will route around this issue. Thank you.

**Comment by dhermes** [comment] 2015-06-07 21:31
It may still be a bash/encoding issue. How do you set the variable?

I would do

```
$ VAR_NAME=$(cat filename.p12)
```

**Comment by migurski** [comment] 2015-06-08 04:52
The variable is being set by Honcho, which reads a file of environment vars in `VAR=value` form. The invocation looks like this:

    honcho -e .env run python google-test.py

The contents are [as above](https://github.com/google/oauth2client/issues/193#issuecomment-107765444), with a line like this:

    GDOCS_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nNNNNNN\nNNNNNN\nNNNNNN\n-----END PRIVATE KEY-----\n"

The md5 assertion gives me confidence that the value is coming through identically on both platforms.

**Comment by migurski** [comment] 2015-06-09 05:08
I’m getting nowhere with the JSON route, by the way. Trying this:

```python
with open('/tmp/JSON-key-from-Developers-Console.json') as file:
    credentials = SignedJwtAssertionCredentials.from_json(file.read())
    gc = gspread.authorize(credentials)
```

…results in this:

```
Traceback (most recent call last):
  File "scripts/google-failure.py", line 22, in <module>
    credentials = SignedJwtAssertionCredentials.from_json(file.read())
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/oauth2client/client.py", line 1527, in from_json
    data['service_account_name'],
KeyError: 'service_account_name'
```

The file I retrieved from the console looks like this:

```json
{
  "private_key_id": "nnnnnnn",
  "private_key": "-----BEGIN PRIVATE KEY-----\nNNNNNNN\nNNNNNNN\nNNNNNNN\n-----END PRIVATE KEY-----\n",
  "client_email": "nnnnnnn@developer.gserviceaccount.com",
  "client_id": "nnnnnnn.apps.googleusercontent.com",
  "type": "service_account"
}
```

That’s on the 10.9.5 Mac. I’m available to talk via e-mail or Hangout if more detail would be helpful, but just not having a lot of luck with service accounts here.

**Comment by dhermes** [comment] 2015-06-09 05:21
Can you try the [following][1]:

```python
from oauth2client.client import _get_application_default_credential_from_file
json_credentials_path = 'filename.json'
credentials = _get_application_default_credential_from_file(
    json_credentials_path)
```

and post a stack trace if there are issues?

You could also set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable in `bash` / other shell:

```bash
export GOOGLE_APPLICATION_CREDENTIALS="filename.json"
```

and then just execute

```python
from oauth2client.client import GoogleCredentials
credentials = GoogleCredentials.get_application_default()
```

----

Sorry for the confusion / bad naming. IIUC the `SignedJwtAssertionCredentials.from_json` factory is meant for deserialization of an existing `oauth2client` credential, not for the language-agnostic JSON key file you downloaded from the cloud console.

[1]: https://github.com/google/oauth2client/issues/192#issuecomment-110119978

**Comment by dhermes** [comment] 2015-06-09 05:22
If this doesn't work, let's hop on hangouts tomorrow.

**Comment by migurski** [comment] 2015-06-09 05:36
Seeing this, unsure where to put the scopes in this case:

```
Traceback (most recent call last):
  File "scripts/google-failure.py", line 23, in <module>
    gc = gspread.authorize(credentials)
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/gspread/client.py", line 335, in authorize
    client.login()
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/gspread/client.py", line 98, in login
    self.auth.refresh(http)
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/oauth2client/client.py", line 598, in refresh
    self._refresh(http.request)
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/oauth2client/client.py", line 769, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/migurski/Sites/Code-for-America-People-DB/venv2-peopledb/lib/python2.7/site-packages/oauth2client/client.py", line 834, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
oauth2client.client.AccessTokenRefreshError: invalid_scope: Empty or missing scope not allowed.
```

I’m available in the early morning and late afternoon tomorrow, thank you for the offer! I’ll follow up via email.

**Comment by dhermes** [comment] 2015-06-09 06:29
That's good. It seems you at least got a valid `credentials` object. If you did, then you can add the scopes via

```python
credentials = GoogleCredentials.get_application_default()  # Or the other snippet above
scopes = ['https://spreadsheets.google.com/feeds']  # I assume based on `gspread`
credentials = credentials.create_scoped(scope)
gc = gspread.authorize(credentials)  # I assume, never used `gspread`
```

**Comment by migurski** [comment] 2015-06-09 16:01
Sadly, the JSON method exhibits identical behavior to the non-JSON one: works on Mac, fails on Linux.

**Comment by dhermes** [comment] 2015-06-09 16:32
Let's chat off this thread and see what's happening.

**Comment by dhermes** [comment] 2015-06-09 19:02
Resolving. There was massive time drift on @migurski EC2 instance, so the timestamps were already expired.

@anthmgoogle It'd be great if Google provided more than just `invalid_grant` in the error payload.

To debug @migurski and I had to step into the JWT creation code and break apart to see how each segment was being signed. Luckily that was not the issue, and the time drift became clear.

**Closed by dhermes** 2015-06-09 19:02 UTC

**Comment by migurski** [comment] 2015-06-09 19:09
:+1: :+1: :+1: 

Thank you for helping me debug this, @dhermes.

**Comment by dhermes** [comment] 2015-06-23 19:35
Has an internal Google bug been filed with the identity team yet?

Easy to file issue:

```
Error message should include message about invalid timestamps.

User on a machine with clock drift received `{'error': `invalid_grant`}` and no other context when trying to get an access token for a service account. Finding the root cause (the clock drift on the machine) required digging fully into the source code of the client library to check that the payload was being signed correctly and to analyze each section of the JWT sent.

See https://github.com/google/oauth2client/issues/193.
```

/cc @nathanielmanistaatgoogle @anthmgoogle

**Comment by jameserrico** [comment] 2015-08-18 14:23
Guys I just wanted to thank you for this detailed information.  I had the same exact issue and tracking it down was a nightmare.  I probably would not have guessed the timedrift had it not been for this AWESOME information.

**Comment by migurski** [comment] 2015-08-18 15:08
:watch: :100:

**Comment by dhermes** [comment] 2015-08-18 15:34
Great to hear it :+1:

**Comment by vstoykov** [comment] 2015-09-29 13:07
From 5 days I have the same problem until I found this issue and realized that the time of my server was wrong. Now I installed ntp to prevent future problems.

Definitely a better error message is needed!

**Comment by dhermes** [comment] 2015-09-29 17:05
Glad to see we've been able to help some people with our deep dive.

AFAIK @nathanielmanistaatgoogle has filed an internal bug to track this issue.

**Comment by aneximandros** [comment] 2015-11-11 09:55
Thank you so much, super helpful. I couldn't have traced this error without your help. I turned off 'set date and time automatically" a long time ago and totally forgot about it. After turning it back on, the error disappeared. This was on the latest macbook pro.

**Comment by migurski** [comment] 2015-11-11 18:42
Good to know, @aneximandros!

**Comment by nabilahmad** [comment] 2015-11-24 22:16
Thanks a ton guys! I was having the exact same issue, under win2k8r2

**Comment by syhpoon** [comment] 2015-12-22 18:17
Thanks, this really helped! Otherwise the error was really weird, the same code worked on my local machine and didn't work on the server.

**Comment by Dmitrii-I** [comment] 2016-01-26 18:03
Thanks everyone. I had same issue with time drift. I guess I should use ntpd... The library could also provide better error messages.

**Comment by dhermes** [comment] 2016-01-26 20:19
@Dmitrii-I thanks for the suggestion! The problem is that it's impossible to distinguish if `invalid_grant` comes from a bad payload caused by the crypto failing or if it's caused by a bad timestamp or anything else. I suppose we could add a "maybe this is the problem" to the error message, but it wouldn't necessarily narrow it down.

@nathanielmanistaatgoogle Any update on a better error message from the server?

**Comment by nathanielmanistaatgoogle** [comment] 2016-02-04 22:05
@dhermes: everyone agrees that it should be done and it's a work item getting routed between a few different people and teams.

**Comment by dhermes** [comment] 2016-02-05 13:01
Good to hear. Seems this issue has become a popular reference point for people.
