### ISSUE TITLE
Can we trust GAE bundled pycrypto?

### ISSUE THREAD

**Issue by cyluss** [google/oauth2client#512] opened 2016-05-24 06:39 UTC
Affecting version: 2.0.1 and above

I have been using oauth2client and today I found some quirks on pycrypto.

I have two tokens which is from Android app signed by Google Sign in library. Both tokens are verified by pycrypto verifier, one is passing the other is failing with `ValueError: Plaintext too large`. I got it working by falling back to pure python verifier manually.

Is there any reason for falling back to pycrypto after failing to import OpenSSL? I can't depend on pycrypto anymore although it is bundled in GAE runtime.

```
   idinfo = client.verify_id_token(self.id_token, setting['google_web_oauth2_client_id'])
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/client.py", line 1679, in verify_id_token
    return crypt.verify_signed_jwt_with_certs(id_token, certs, audience)
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/crypt.py", line 240, in verify_signed_jwt_with_certs
    _verify_signature(message_to_sign, signature, certs.values())
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/crypt.py", line 119, in _verify_signature
    if verifier.verify(message, signature):
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/_pycrypto_crypt.py", line 52, in verify
    SHA256.new(message), signature)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/Signature/PKCS1_v1_5.py", line 148, in verify
    m = self._key.encrypt(S, 0)[0]
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/RSA.py", line 150, in encrypt
    return pubkey.pubkey.encrypt(self, plaintext, K)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/pubkey.py", line 75, in encrypt
    ciphertext=self._encrypt(plaintext, K)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/RSA.py", line 224, in _encrypt
    return (self.key._encrypt(c),)
ValueError: Plaintext too large
```

**Comment by jonparrott** [comment] 2016-05-24 17:01
I'm not sure what you mean by the question "Can we trust GAE bundled PyCrypto". It's PyCrypto, we haven't made any significant changes other than putting it within our sandbox.

It does seem interesting that you're getting that error. Are you able to reproduce this outside of App 
Engine using PyCrypto 2.6?

**Comment by jonparrott** [comment] 2016-05-24 17:06
There's some interesting stuff in these threads:

https://code.google.com/p/googleappengine/issues/detail?id=12516
https://code.google.com/p/googleappengine/issues/detail?id=10753

Please do not share your ID tokens publicly, but can you tell any significant difference between the id tokens that succeed and the ones that fail?

**Comment by jonparrott** [comment] 2016-06-10 16:33
I'm closing this as you haven't responded in several days, if you have further questions here please feel free to respond.

**Closed by jonparrott** 2016-06-10 16:33 UTC
Labels: question

**Comment by dgaedcke** [comment] 2016-07-17 18:45
Hey Jon....we just upgraded from Gitkit to Firebase-Auth and we're hitting this error again....
I don't know if you've heard or seen anything that gives you more insight into what might be happening here??  In the absence of a specific suggestion to prevent it, could you please explain:

1.  What's the interaction between the keys on the  Console->Api Manager->Credentials page, and those on the Console->IAM & Admin->Service accounts?  It seems new ones were auto-created when we imported our Project into the Firebase Console?
2.  Does the switch to Firebase on the IOS client require any config change on the Python server?  This is what we're currently doing:
`server_config_json = path.join(path.dirname(path.realpath(__file__)), 'gitkit-server-config.json')
gitkitClient = GitkitClient.FromConfigFile(server_config_json)`
and that json file points to a:  <key-prefix>.p12 file which (I believe) was generated with one of our server-keys.
3. How do we know WHICH of the multiple api-keys to use on the IOS side?

Thanks,
Dewey

**Comment by jonparrott** [comment] 2016-07-18 17:03
I am not familiar with Firebase, I'll see if I can get someone who can help.

**Comment by liujin-google** [comment] 2016-07-18 19:18
Hi Dewey - can you elaborate which tokens your server is trying to verify? Firebase Auth token, Gitkit token, and Google Sign In tokens are all different.
1. Service accounts in Console->Api Manager->Credentials should be the same as  Console->IAM & Admin->Service accounts. API Keys are listed in Api Manager->Credentials but they do not belong to IAM & Admin->Service accounts.
2. Your server needs to verify Firebase Authentication tokens https://firebase.google.com/docs/auth/server/verify-id-tokens#verify_id_tokens_using_the_firebase_sdk or https://firebase.google.com/docs/auth/server/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library.
3. You can check your iOS app to see which API key is used: https://developers.google.com/identity/toolkit/ios/#about_the_configuration_values

**Comment by dgaedcke** [comment] 2016-07-18 19:29
It is the JWT returned from:
user?.getTokenForcingRefresh(true) {idToken, error in ...

On the GAE server (Python), we have this code:
`server_config_json = path.join(path.dirname(path.realpath(__file__)), 'gitkit-server-config.json')

gitkitClient = GitkitClient.FromConfigFile(server_config_json)

gitkitUserObj = gitkitClient.VerifyGitkitToken(access_token)`

When we send JWT from Gitkit, we get a real user Obj in "gitkitUserObj"
When we send JWT from FirebaseAuth, "gitkitUserObj" is None....
and once (not every time) we got the "ValueError: Plaintext too large"  (subject of this thread)

Since nothing on the server-side has changed, I'm confused by the failure.....
I'll go read the links you've provided....and thanks very much for lending us your expertise

**Comment by dgaedcke** [comment] 2016-07-18 19:45
Interestingly, after reading your links, I went to [this page](https://kjur.github.io/jsrsasign/tool_jwtveri.html), to validate the FirAuth JWT.  Even without a key being added to the page, it seemed to decode the token (showed me users name, user_id, picture, sign_in_provider....everything except his email), but that page said token was invalid....
It also showed me: 
{
  "alg": "RS256",
  "kid": "6ccf3d0a5557bb68533c052ee0ce....."
}
but there is no key in our account starting with 6ccf3.....
I'm pretty baffled....

**Comment by liujin-google** [comment] 2016-07-18 22:15
The kid 6ccf3... is owned by Firebase Auth server to sign Firebase Auth tokens. You can grab the public cert of it from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com and use a JWT library to verify the signature.

**Comment by dgaedcke** [comment] 2016-07-18 22:26
so you are saying we should not use our own API key or .p12 file to decrypt these JWT's but we should use YOUR public one??  If so, thats a major change from the way we've been decrypting the JWT's we get from the old Gitkit.   I'm more confused than ever....can you explain that to me?

**Comment by dgaedcke** [comment] 2016-07-18 22:42
As addl. info, "6ccf3" is not found on the page you linked.
And we've been successfully parsing our GitKit JWT's for many months using the following approach

`server_config_json = path.join(path.dirname(path.realpath(__file__)), 'gitkit-server-config.json')
gitkitClient = GitkitClient.FromConfigFile(server_config_json)
def gitTokenToGitkitUserObj(access_token):
    err = None
    try:
        gitkitUserObj = gitkitClient.VerifyGitkitToken(access_token)
        if gitkitUserObj is None:
            err = 'Gitkit token could not be unpacked...check your secret'`

**Comment by liujin-google** [comment] 2016-07-19 00:40
Dewey - no worries :) The way to verify the old Gitkit token and new Firebase token are almost exactly the same. When you call GitkitClient.VerifyGitkitToken(),  the GitkitClient actually also fetches the public cert of Gitkit server (using API key or p12 file) to verify the token, .

The reason to use Gitkit/Firebase public keys is to ensure that the token are indeed signed by Gitkit/Firebase, not someone else. To guarantee that, Gitkit/Firebase server owns the private RSA256 key which is securely protected in Google infrastructure.

Gitkit (same for Firebase Auth) public keys are rotated periodically. It could be that "6ccf3" key has expired.

**Comment by dgaedcke** [comment] 2016-07-19 01:53
so if the "the GitkitClient actually also fetches the public cert of Gitkit server", then this should be working with the JWT's from both Gitkit & FirAuth.......but I completed the Facebook login and got our latest token just hours ago and the same problem persists.....with the Gitkit token, I get a UserObject back, and with the FirAuth Token, I get None back.....

So you have comforted me that nothing major has changed, but that's also a bummer because I'm still at a loss as to why it's not working....

**Comment by dgaedcke** [comment] 2016-07-20 19:53
I've been in communication with Firebase support and they advise us to ABANDON the gitkit client on the server entirely and simply use a PyJWT to decode the token into a dictionary.   Can you offer and support or cautions with this advice??

**Comment by liujin-google** [comment] 2016-07-20 20:30
The public cert of Gitkit and Firebase server are different, and the Gitkit client library does not recognize the Firebase tokens.

Before Firebase server SDK will support Python, you may use some third party libraries to verify the Firebase token. If there are issues within the third party libraries, it is up to the library owner to fix the issues.

**Comment by dgaedcke** [comment] 2016-07-20 20:54
That's really helpful...finally an explanation of why it's been failing.  Thank you so much!!

Hopefully my last question, the instructions on [this page](https://firebase.google.com/docs/auth/server/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library) say:
"Grab the public key from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com and use a JWT library to verify the signature"

But up above, you mentioned that the keys get rotated out periodically for security reasons.....
So if we copy the key to use with PyJWT, won't it suddenly break when that key gets rotated out of service??
Thanks again for clarifying this for me!!

**Comment by dgaedcke** [comment] 2016-07-21 18:02
Above, you mentioned that the keys get rotated out periodically for security reasons.....
So if we copy the key to use with PyJWT, won't it suddenly break when that key gets rotated out of service??
Thanks again for clarifying this for me!!

**Comment by liujin-google** [comment] 2016-07-21 18:10
Right - the Firebase public key should not be hard coded into your app. Instead, the keys should be cached, and re-downloaded periodically or on demand.

According to the http response of the public key endpoint https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com, the cache period should be less than ~ 6 hours (23808 seconds).

**Comment by AjayTripathy** [comment] 2017-01-28 00:26
Hello, I ran into this issue today and believe I was able to track it down to an unexpected error being thrown by PyCrypto. https://github.com/dlitz/pycrypto/issues/161

Here's my theory of what is going on. When you try and verify the jwt, you try and verify across all possible keys supplied by https://www.googleapis.com/identitytoolkit/v3/relyingparty/publicKeys (or whatever corresponding endpoint contains the list of the corresponding public keys that sign the jwt)

All but one of these public keys are invalid. But, one of them has signed the jwt credentials and we need to find which one.  The oauth2 client does it here: 
https://github.com/google/oauth2client/blob/master/oauth2client/crypt.py#L118

The problem is that pycrypto will sometimes throw an error on invalid keys as described in the above Pycrypto issue. The error is uncaught and propagates. This bug has appeared transiently because the keys are rotated, and if them public key that happens to have signed the user's jwt is higher in the list, you won't see an error. You also won't see the error 

The right thing to do is probably to fix pycrypto but given the relative level of difficulty in patching AppEngine's pycrypto, I deployed the following oauth2client workaround today and the errors are gone:
https://github.com/google/oauth2client/compare/master...AjayTripathy:patch-1

As I have only encountered this today, I have not had time to write a failing test but I imagine it would go like this, but hopefully this patch provides a starting point for people encountering this problem.

**Comment by dhermes** [comment] 2017-01-28 01:34
@AjayTripathy a few quick notes:

- PyCrypto is essentially deprecated (i.e. the maintainer says "don't use this")
- There is a [pure Python implementation][1] of crypto helpers in this library. By default (as you can see from the linked code) if `pyOpenSSL` or `PyCrypto` are installed, those will be the default, but you can manually set the default if you like
- It's tough to comment on the issue you describe without a stacktrace and some suggestions / snippets to reproduce

[1]: https://github.com/google/oauth2client/blob/cc3e7d13a4f33cb10ce8fe2acfe02b853b1774c3/oauth2client/crypt.py#L70-L71

**Comment by AjayTripathy** [comment] 2017-01-28 02:06
Sorry, the stacktrace is very similar to the original one in this issue:
```
  idinfo = client.verify_id_token(self.id_token, setting['google_web_oauth2_client_id'])
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/client.py", line 1679, in verify_id_token
    return crypt.verify_signed_jwt_with_certs(id_token, certs, audience)
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/crypt.py", line 240, in verify_signed_jwt_with_certs
    _verify_signature(message_to_sign, signature, certs.values())
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/crypt.py", line 119, in _verify_signature
    if verifier.verify(message, signature):
  File "/base/data/home/apps/s~jackmic-production/api:1.393007236872492345/lib/oauth2client/_pycrypto_crypt.py", line 52, in verify
    SHA256.new(message), signature)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/Signature/PKCS1_v1_5.py", line 148, in verify
    m = self._key.encrypt(S, 0)[0]
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/RSA.py", line 150, in encrypt
    return pubkey.pubkey.encrypt(self, plaintext, K)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/pubkey.py", line 75, in encrypt
    ciphertext=self._encrypt(plaintext, K)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/pycrypto-2.6/Crypto/PublicKey/RSA.py", line 224, in _encrypt
    return (self.key._encrypt(c),)
ValueError: Plaintext too large
```

Reproducing is...difficult. I have a repro I can't share with you because it involves a real user cookie and the exact state of the keys in https://www.googleapis.com/identitytoolkit/v3/relyingparty/publicKeys

You could potentially repro by:
1. Create a jwt and sign in with a private key.
2. Create a public key-private key pair such that key.n < bytes_to_long(signature). IE, create a key that reproduces https://github.com/dlitz/pycrypto/issues/161 . 
3. Attempt to use that key as the cert passed in to https://github.com/google/oauth2client/blob/master/oauth2client/crypt.py#L207 

I appreciate that PyCrypto is deprecated but a ton of AppEngine apps use it (including likely all python apps relying on the old Google Identity Toolkit) because it's the default crypto library that's in the python AppEngine environment. 

As you note, PyCrypto is deprecated so I'm not suggesting that we re-open this issue or pull my patch into master-- just supplying my research and patch as a jumping off point for anyone else experiencing this problem. Another solution would be to vendor a pure python crypto library to your appengine instance and configure oauth2client to use that instead.
