### ISSUE TITLE
OAuth2Credentials.apply() fails

### ISSUE THREAD

**Issue by ericbuehl** [google/oauth2client#632] opened 2016-08-18 20:46 UTC
If one calls OAuth2Credentials.apply() using GoogleCredentials.get_application_default() from within GCE, access_token is not populated and results in a None reference error.

Currently I am hacking around this by calling credentials.get_access_token() before credentials.apply(headers)

**Comment by jonparrott** [comment] 2016-08-18 20:51
This is a duplicate of #343.

**Closed by jonparrott** 2016-08-18 20:51 UTC
