### ISSUE TITLE
application default credentials don't respect CLOUDSDK_CONFIG

### ISSUE THREAD

**Issue by skelterjohn** [google/oauth2client#151] opened 2015-03-27 14:10 UTC
application default credentials should either be written to "$CLOUDSDK_CONFIG/application_default_credentials.json", with CLOUDSDK_CONFIG defaulting to "~/.config/gcloud".

gcloud promises that it won't write any credential information outside of $CLOUDSDK_CONFIG.

**Comment by skelterjohn** [comment] 2015-03-27 14:13
At the very least, it should ensure that directory exists before writing. This bug was discovered by the ADCs failing to write.

**Comment by anthmgoogle** [comment] 2015-03-30 17:58
#154 is a dupe of this:

https://feedback.corp.google.com/#/Report/5019840888

Description:
"gcloud auth login" fails due to .config/gcloud directory not existing

It looks to be a bug that "gcloud auth login" fails when CLOUDSDK_CONFIG is set to non-default location. Either credentials should be stored in the location specified by CLOUDSDK_CONFIG or the parent directories for the default location should be created before attempting to save the credential. The former seems cleaner but there are probably some good reasons behind using a fixed location here.

**Comment by dhermes** [comment] 2015-04-10 21:54
I can fix this. Drafting PR now.

**Comment by dhermes** [comment] 2015-04-10 22:23
#162 sent

I debated adding a call to `os.mkdir` but I think that's better left to the `gcloud` CLI or the user that has set `$CLOUDSDK_CONFIG` manually.

**Comment by dhermes** [comment] 2015-04-29 16:55
@anthmgoogle I've got a fix ready in #162. Any issues with it?

**Closed** 2015-04-29 19:34 UTC
