### ISSUE TITLE
GoogleCredentials.get_application_default broken on GAE in 3.0.0

### ISSUE THREAD

**Issue by awh** [google/oauth2client#582] opened 2016-08-02 12:49 UTC
#570 reversed the order of credential resolution so that files are now checked before GAE context. Unfortunately `_implicit_credentials_from_files` is broken on GAE due to a dependency on the `pwd` module which is not present in that environment:
```
ImportError: No module named pwd
at expanduser (/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py:268)
at _get_well_known_file (/base/data/home/apps/XXX/lib/oauth2client/client.py:1392)
at _implicit_credentials_from_files (/base/data/home/apps/XXX/lib/oauth2client/client.py:1226)
at _get_implicit_credentials (/base/data/home/apps/XXX/lib/oauth2client/client.py:1273)
at get_application_default (/base/data/home/apps/XXX/lib/oauth2client/client.py:1288)
```

**Comment by jonparrott** [comment] 2016-08-02 16:34
This is a duplicate of #578. There are more details and workarounds documented there. Please respond to that issue if you have any further questions/concerns.

**Closed by jonparrott** 2016-08-02 16:34 UTC
